/*
 * DIO_cfg.h
 *
 *  Created on: Jul 12, 2022
 *      Author: Hythm Saad Khalifa
 */

#ifndef DRIVERS_MCAL_DIO_DIO_CFG_H_
#define DRIVERS_MCAL_DIO_DIO_CFG_H_

#define DIO_DIR_P0_PORTA	DIO_INPUT
#define DIO_DIR_P1_PORTA	DIO_INPUT
#define DIO_DIR_P2_PORTA	DIO_INPUT
#define DIO_DIR_P3_PORTA	DIO_INPUT
#define DIO_DIR_P4_PORTA	DIO_INPUT
#define DIO_DIR_P5_PORTA	DIO_INPUT
#define DIO_DIR_P6_PORTA	DIO_INPUT
#define DIO_DIR_P7_PORTA	DIO_INPUT

#define DIO_DIR_P0_PORTB	DIO_INPUT
#define DIO_DIR_P1_PORTB	DIO_INPUT
#define DIO_DIR_P2_PORTB	DIO_INPUT
#define DIO_DIR_P3_PORTB	DIO_INPUT
#define DIO_DIR_P4_PORTB	DIO_INPUT
#define DIO_DIR_P5_PORTB	DIO_INPUT
#define DIO_DIR_P6_PORTB	DIO_INPUT
#define DIO_DIR_P7_PORTB	DIO_INPUT

#define DIO_DIR_P0_PORTC	DIO_INPUT
#define DIO_DIR_P1_PORTC	DIO_INPUT
#define DIO_DIR_P2_PORTC	DIO_INPUT
#define DIO_DIR_P3_PORTC	DIO_INPUT
#define DIO_DIR_P4_PORTC	DIO_INPUT
#define DIO_DIR_P5_PORTC	DIO_INPUT
#define DIO_DIR_P6_PORTC	DIO_INPUT
#define DIO_DIR_P7_PORTC	DIO_INPUT

#define DIO_DIR_P0_PORTD	DIO_INPUT
#define DIO_DIR_P1_PORTD	DIO_INPUT
#define DIO_DIR_P2_PORTD	DIO_INPUT
#define DIO_DIR_P3_PORTD	DIO_INPUT
#define DIO_DIR_P4_PORTD	DIO_INPUT
#define DIO_DIR_P5_PORTD	DIO_INPUT
#define DIO_DIR_P6_PORTD	DIO_INPUT
#define DIO_DIR_P7_PORTD	DIO_INPUT



#define DIO_VAL_P0_PORTA	DIO_INPUT_FLAOTING
#define DIO_VAL_P1_PORTA	DIO_INPUT_FLAOTING
#define DIO_VAL_P2_PORTA	DIO_INPUT_FLAOTING
#define DIO_VAL_P3_PORTA	DIO_INPUT_FLAOTING
#define DIO_VAL_P4_PORTA	DIO_INPUT_FLAOTING
#define DIO_VAL_P5_PORTA	DIO_INPUT_FLAOTING
#define DIO_VAL_P6_PORTA	DIO_INPUT_FLAOTING
#define DIO_VAL_P7_PORTA	DIO_INPUT_FLAOTING

#define DIO_VAL_P0_PORTB	DIO_INPUT_FLAOTING
#define DIO_VAL_P1_PORTB	DIO_INPUT_FLAOTING
#define DIO_VAL_P2_PORTB	DIO_INPUT_FLAOTING
#define DIO_VAL_P3_PORTB	DIO_INPUT_FLAOTING
#define DIO_VAL_P4_PORTB	DIO_INPUT_FLAOTING
#define DIO_VAL_P5_PORTB	DIO_INPUT_FLAOTING
#define DIO_VAL_P6_PORTB	DIO_INPUT_FLAOTING
#define DIO_VAL_P7_PORTB	DIO_INPUT_FLAOTING

#define DIO_VAL_P0_PORTC	DIO_INPUT_FLAOTING
#define DIO_VAL_P1_PORTC	DIO_INPUT_FLAOTING
#define DIO_VAL_P2_PORTC	DIO_INPUT_FLAOTING
#define DIO_VAL_P3_PORTC	DIO_INPUT_FLAOTING
#define DIO_VAL_P4_PORTC	DIO_INPUT_FLAOTING
#define DIO_VAL_P5_PORTC	DIO_INPUT_FLAOTING
#define DIO_VAL_P6_PORTC	DIO_INPUT_FLAOTING
#define DIO_VAL_P7_PORTC	DIO_INPUT_FLAOTING

#define DIO_VAL_P0_PORTD	DIO_INPUT_FLAOTING
#define DIO_VAL_P1_PORTD	DIO_INPUT_FLAOTING
#define DIO_VAL_P2_PORTD	DIO_INPUT_FLAOTING
#define DIO_VAL_P3_PORTD	DIO_INPUT_FLAOTING
#define DIO_VAL_P4_PORTD	DIO_INPUT_FLAOTING
#define DIO_VAL_P5_PORTD	DIO_INPUT_FLAOTING
#define DIO_VAL_P6_PORTD	DIO_INPUT_FLAOTING
#define DIO_VAL_P7_PORTD	DIO_INPUT_FLAOTING



#endif /* DRIVERS_MCAL_DIO_DIO_CFG_H_ */
